#!/bin/bash

# Introduce: https://github.com/sohaha/git-hook
# Version:   v1.0.0
# git config core.hooksPath .githook

set -e

msg=$(head -n 1 "$1")

if echo "$msg" | grep -iqE "^Merge "; then
  exit 0
fi;

if echo "$msg" | grep -iqE "^Revert "; then
  exit 0
fi;

if echo "$msg" | grep -iqE "^(feat|fix|docs|style|refactor|perf|test|chore|WIP|init|ci|misc)(\([^()]{1,}\)){0,1}: .{1,}"; then
  exit 0
fi;

echo -e "不规范提交，正确方式: [类型: 简单描述]"
echo 
cat <<EOF
可用类型及其含义：
  feat:     新功能
  fix:      BUG修复
  docs:     文档更改
  style:    代码风格修正，不影响代码功能（空格，格式化，缺少分号等）
  refactor: 重构，代码更改既不修复错误也不添加功能
  perf:     提升代码性能
  test:     添加缺失的测试或更正现有的测试
  revert:   代码回滚
  WIP:      工作正在进行中
  chore:    非项目或测试文件的更改，例如更新构建任务﹑程序包管理器
  init:     初次提交
  ci:       持续集成
  misc:     其他杂项
EOF
echo

exit 1
